# Generated by Django 3.2.7 on 2021-11-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0001_initial'),
        ('users', '0002_user_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_achievements',
            name='achievement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Achievements.achievement'),
        ),
    ]
