# Generated by Django 3.2.7 on 2021-11-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0001_initial'),
        ('users', '0003_alter_user_achievements_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_achievements',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievements.achievement'),
        ),
    ]
