# Generated by Django 3.2.7 on 2021-11-11 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Achievements', '0001_initial'),
        ('users', '0004_alter_user_achievements_achievement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_achievements',
            unique_together={('user', 'achievement')},
        ),
    ]
