# Generated by Django 3.2.7 on 2021-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupalActivities', '0003_alter_groupactivity_type'),
        ('users', '0005_alter_user_achievements_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='completed_group_activities',
            field=models.ManyToManyField(related_name='completed', to='grupalActivities.GroupActivity'),
        ),
    ]
