# Generated by Django 3.2.7 on 2021-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalActivities', '0002_auto_20211013_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalactivites',
            old_name='imageURL',
            new_name='image_URL',
        ),
        migrations.RenameField(
            model_name='personalactivites',
            old_name='videoURL',
            new_name='video_URL',
        ),
        migrations.AddField(
            model_name='personalactivites',
            name='categories',
            field=models.ManyToManyField(to='personalActivities.ActivityCategory'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
