# Generated by Django 3.2.7 on 2021-10-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalActivities', '0003_auto_20211013_1336'),
    ]

    operations = [
        
    ]
