# Generated by Django 3.2.7 on 2021-10-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalActivities', '0004_remove_personalactivites_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalactivites',
            name='temporal',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='personalactivites',
            name='experience',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
