# Generated by Django 3.2.7 on 2021-10-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalActivities', '0005_auto_20211024_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalactivites',
            name='temporal',
        ),
    ]
