# Generated by Django 3.2.7 on 2021-11-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('gender', models.CharField(max_length=254)),
            ],
        ),
    ]
