# Generated by Django 3.2.7 on 2021-10-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupalActivities', '0002_alter_groupactivity_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupactivity',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
