# Generated by Django 3.2.7 on 2021-11-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalActivities', '0002_alter_personalactivites_experience'),
        ('grupalActivities', '0003_alter_groupactivity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=254)),
                ('dateTime', models.DateTimeField()),
                ('address', models.CharField(max_length=254)),
                ('contact', models.CharField(max_length=254)),
                ('capacity', models.IntegerField(default=0)),
                ('assistants', models.ManyToManyField(related_name='assisted_ev', to=settings.AUTH_USER_MODEL)),
                ('categoriy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalActivities.activitycategory')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
