# Generated by Django 3.2.7 on 2021-11-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupalActivities', '0004_especialevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialevent',
            old_name='categoriy',
            new_name='category',
        ),
    ]
