# Generated by Django 3.2.7 on 2021-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupalActivities', '0005_rename_categoriy_especialevent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialevent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
