# Generated by Django 3.2.7 on 2021-10-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalActivities', '0001_initial'),
        ('grupalActivities', '0002_alter_groupactivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupactivity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalActivities.activitycategory'),
        ),
    ]
