# Generated by Django 3.2.7 on 2021-10-26 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalActivities', '0001_initial'),
        ('encuesta', '0001_initial'),
        ('grupalActivities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date start')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='date finish')),
                ('status', models.CharField(default='started', max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalActivities.personalactivites')),
                ('encuesta', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='encuesta.encuesta')),
            ],
            options={
                'verbose_name': 'User_activity',
                'verbose_name_plural': 'User_activitys',
            },
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('activities', models.ManyToManyField(through='users.User_activity', to='personalActivities.PersonalActivites')),
                ('group_activities', models.ManyToManyField(to='grupalActivities.GroupActivity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile'),
        ),
    ]
