# Generated by Django 3.2.7 on 2021-10-25 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_remove_encuesta_user'),
        ('users', '0002_auto_20211023_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activity',
            name='encuesta',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='encuesta.encuesta'),
        ),
    ]
