# Generated by Django 3.2.7 on 2021-11-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
